CREATE TABLE users(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    password VARCHAR(255),
    token VARCHAR(255),
    at_update DATETIME
)ENGINE = InnoDB;
CREATE TABLE posts(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    body TEXT,
    user_id INTEGER UNSIGNED,
    at_update DATETIME,
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)ENGINE = InnoDB;
CREATE TABLE comments(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    body VARCHAR(255),
    user_id INTEGER UNSIGNED,
    post_id INTEGER UNSIGNED,
    at_update DATETIME,
    FOREIGN KEY (`post_id`)
    REFERENCES `posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)ENGINE = InnoDB;
CREATE TABLE albuns(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    description TEXT,
    user_id INTEGER UNSIGNED,
    at_update DATETIME,
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)ENGINE = InnoDB;
CREATE TABLE photos(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    album_id INTEGER UNSIGNED,
    at_update DATETIME,
    FOREIGN KEY (`album_id`)
    REFERENCES `albuns` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)ENGINE = InnoDB;